{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged",
    "module": "neoforge",
    "version": "26.1.0.0-alpha.0+snapshot-11.20260307.044334",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-26.1.0.0-alpha.0+snapshot-11.20260307.044334-sources.jar",
          "url": "neoforge-26.1.0.0-alpha.0+snapshot-11.20260307.044334-sources.jar",
          "size": 1992572,
          "sha512": "f45114d08b0267b4e94511173f5bc0a09940d22937f7ac5438adaf40397376e450769f81673a6ceae8735d597fa0c88a9fc6deea001a23011af36f8bd2f817d0",
          "sha256": "60725cccdfaf8bf2718b9e644a53400d066267a617f6e06186e082cffcf4e8e8",
          "sha1": "087cb0e6047b4a5dc83b5cad9a48b76f5d6be589",
          "md5": "2bd9cc3adb9b6e45fdb492cd71036f11"
        }
      ]
    },
    {
      "name": "modDevBundle",
      "attributes": {
        "org.gradle.category": "data",
        "org.gradle.dependency.bundling": "external"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "26.1-snapshot-11-1"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "neoforge-26.1.0.0-alpha.0+snapshot-11.20260307.044334-userdev.jar",
          "url": "neoforge-26.1.0.0-alpha.0+snapshot-11.20260307.044334-userdev.jar",
          "size": 4432316,
          "sha512": "f2ea5709521791adb108522e080bd519d2b9f243723bcf78a2e3e5e98452c445ad0d45fcb2747f3bef70e4edec87d36f616c6e12995449cff695b32975370617",
          "sha256": "58efbdfd3b7e5350fa4138e69330f5d12bb6af6254f0dd613860156d777c5fc8",
          "sha1": "28e4553a7dfac3f4b2db8d50706e5a9426eec400",
          "md5": "648449eda16b33a9bcd04cc916eb21cd"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-bundle",
          "version": "26.1.0.0-alpha.0+snapshot-11.20260307.044334"
        }
      ]
    },
    {
      "name": "modDevConfig",
      "attributes": {
        "org.gradle.category": "data",
        "org.gradle.dependency.bundling": "external"
      },
      "files": [
        {
          "name": "neoforge-26.1.0.0-alpha.0+snapshot-11.20260307.044334-moddev-config.json",
          "url": "neoforge-26.1.0.0-alpha.0+snapshot-11.20260307.044334-moddev-config.json",
          "size": 7204,
          "sha512": "793e24c08647cfdda8fc860256b40c4aafb5fcd547788511b6c592c73399e8566ee3293f8b1426b87ce771b7bbd204887ff80140613562cfb73d37ef86bb83b4",
          "sha256": "05a71adc8f52823f6d1eaefd6ac445891d582c8b09d8f6af39a36093b3a02bf3",
          "sha1": "37feb9df437262782d6b6f57a3fc791299e3fa65",
          "md5": "70ff45f0c0f7e4dc4e9583a58669e301"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-config",
          "version": "26.1.0.0-alpha.0+snapshot-11.20260307.044334"
        }
      ]
    },
    {
      "name": "installerJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-26.1.0.0-alpha.0+snapshot-11.20260307.044334-installer.jar",
          "url": "neoforge-26.1.0.0-alpha.0+snapshot-11.20260307.044334-installer.jar",
          "size": 11161666,
          "sha512": "4a392abbc49e0a05c46d9e6cbc64099950f82c808d784f4d2afc32a57d139ea40813fbebe7d86aacbf3947f4e3f2f8694812dae4e8b538d572bef191bda693e9",
          "sha256": "ecf2c3aa02b8a37c4343db39c4e73c4d49de182901e2af30258487bf230a0cdd",
          "sha1": "5c6376cae2d7eee77c9d11e266cc17de77e9d7d5",
          "md5": "61577e2ebd560e70d7e359aa2a158b65"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-installer",
          "version": "26.1.0.0-alpha.0+snapshot-11.20260307.044334"
        }
      ]
    },
    {
      "name": "universalJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-26.1.0.0-alpha.0+snapshot-11.20260307.044334-universal.jar",
          "url": "neoforge-26.1.0.0-alpha.0+snapshot-11.20260307.044334-universal.jar",
          "size": 7436440,
          "sha512": "83ffc10406c7ca846f7a3ddede66c3896f5ceeef828bfa550ae3b4c520d7a7be5f25a55dd7d26c5256b5f0f076e95ebc82011411c525af0b6da23031f8137a70",
          "sha256": "7b701dd7da239b95716e1238becdbaf82c94a3659b4e9d789416965dd1b7c0a8",
          "sha1": "034f70c8082fe59c30178ba05d82c895a08d8497",
          "md5": "e3c02bf4e8dce55827036b6f845a4c2a"
        }
      ]
    },
    {
      "name": "modDevApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "11.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "earlydisplay",
          "version": {
            "requires": "11.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "org.lwjgl",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "11.0.2"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.7"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.9"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.16.5+mixin.0.8.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "26.1-snapshot-11-1"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform-dependencies"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-dependencies",
          "version": "26.1.0.0-alpha.0+snapshot-11.20260307.044334"
        }
      ]
    },
    {
      "name": "modDevRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "11.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "earlydisplay",
          "version": {
            "requires": "11.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "org.lwjgl",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "11.0.2"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.7"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.9"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.16.5+mixin.0.8.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "26.1-snapshot-11-1"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform-dependencies"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-dependencies",
          "version": "26.1.0.0-alpha.0+snapshot-11.20260307.044334"
        }
      ]
    },
    {
      "name": "modDevModulePath",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external"
      },
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-module-path",
          "version": "26.1.0.0-alpha.0+snapshot-11.20260307.044334"
        }
      ]
    },
    {
      "name": "modDevTestFixtures",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "junit-fml",
          "version": {
            "requires": "11.0.0"
          },
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-test-fixtures",
          "version": "26.1.0.0-alpha.0+snapshot-11.20260307.044334"
        }
      ]
    }
  ]
}
