{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged",
    "module": "neoforge",
    "version": "26.1.0.0-alpha.0+snapshot-6.20260207.040922",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-26.1.0.0-alpha.0+snapshot-6.20260207.040922-sources.jar",
          "url": "neoforge-26.1.0.0-alpha.0+snapshot-6.20260207.040922-sources.jar",
          "size": 1997822,
          "sha512": "c5d7faf2f0f8bdab894cafd3341cbea951fc1d2f08222bad449b9dc9e35e25079b00a5cf007d6d02d3be928faa036c9c8cef63b954a3896a528743a7eafada57",
          "sha256": "b2c2178d82affb498685e20c8f676d7ad113b1cf22083d91df8bd364c346dc1c",
          "sha1": "d65ef88f3f6f6f0c4a9e1bb4096020c57e9e87b3",
          "md5": "5f76b312d1b2c55d85065b95a023c194"
        }
      ]
    },
    {
      "name": "modDevBundle",
      "attributes": {
        "org.gradle.category": "data",
        "org.gradle.dependency.bundling": "external"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "26.1-snapshot-6-1"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "neoforge-26.1.0.0-alpha.0+snapshot-6.20260207.040922-userdev.jar",
          "url": "neoforge-26.1.0.0-alpha.0+snapshot-6.20260207.040922-userdev.jar",
          "size": 4407786,
          "sha512": "549ca4816365adc00ff518c51097772e55f577fe976aad279f616cf54b3d4c88a83f0f685d71df9aaa33d0baf7855f656cad1875900bbec3402ae6e37661f342",
          "sha256": "54821f80211a8cf4fad4077334ce8a6949e1e760ef563c8413fff1200aa41c66",
          "sha1": "62699cd67ac8eb09a7c6c04c8f5d47c1c32337fa",
          "md5": "ea84ef64fe1c10b112cbf77ed6f562ea"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-bundle",
          "version": "26.1.0.0-alpha.0+snapshot-6.20260207.040922"
        }
      ]
    },
    {
      "name": "modDevConfig",
      "attributes": {
        "org.gradle.category": "data",
        "org.gradle.dependency.bundling": "external"
      },
      "files": [
        {
          "name": "neoforge-26.1.0.0-alpha.0+snapshot-6.20260207.040922-moddev-config.json",
          "url": "neoforge-26.1.0.0-alpha.0+snapshot-6.20260207.040922-moddev-config.json",
          "size": 7198,
          "sha512": "706eef530e3f9c2c6aaff45cda92edd26f7ff73485fb2959631fe7719a0c6d03d1cbd3fcba4bfe51f629d6121b03eedb148cf92940eda275aec004f084e8790d",
          "sha256": "87a80d3b8bf1d006317417d52c438826efe6de3523fa140acc2ae43940bc98c7",
          "sha1": "8ff74c109bcc088b32c7894d630b52d7a8a545f8",
          "md5": "7351a533b90ef47ab9fda9fcf4aa462b"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-config",
          "version": "26.1.0.0-alpha.0+snapshot-6.20260207.040922"
        }
      ]
    },
    {
      "name": "installerJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-26.1.0.0-alpha.0+snapshot-6.20260207.040922-installer.jar",
          "url": "neoforge-26.1.0.0-alpha.0+snapshot-6.20260207.040922-installer.jar",
          "size": 11101982,
          "sha512": "c9f44dfd6eea0b25dc0df7a8177eccfa6386b569657ddac05ada96f19b75c503e41a5688378af5d119e0cb86b03d725c1257157e7e460b22b000dc397bc9dc2f",
          "sha256": "97d83cbd99469269b4713254874528b136988ad6e19a4dc44126dd13b2042944",
          "sha1": "241a4b0d05897543469c79cbbd8abbbb96da8daf",
          "md5": "e9fec6fe1c1b3027040ed27261a61413"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-installer",
          "version": "26.1.0.0-alpha.0+snapshot-6.20260207.040922"
        }
      ]
    },
    {
      "name": "universalJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-26.1.0.0-alpha.0+snapshot-6.20260207.040922-universal.jar",
          "url": "neoforge-26.1.0.0-alpha.0+snapshot-6.20260207.040922-universal.jar",
          "size": 7412999,
          "sha512": "83946ca78217d3338a9af1fa88e8d9482c178b97ba003ba2a875254082c536012960e5642b9bfc34f46e61cd775d9819bb8b6cb6bd63fa133ae9e7d7a86dac3f",
          "sha256": "98b1553bdcbf61953f4f3a6826c8696d4e4278f0d974e29c65213172f7a8e61f",
          "sha1": "b6827fc3185c183284737ce6a26bd65c5801b41d",
          "md5": "cee9643688260b58d80fa8322e7a4f7c"
        }
      ]
    },
    {
      "name": "modDevApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "11.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "earlydisplay",
          "version": {
            "requires": "11.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "org.lwjgl",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "11.0.2"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.7"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.9"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.16.5+mixin.0.8.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "26.1-snapshot-6-1"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform-dependencies"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-dependencies",
          "version": "26.1.0.0-alpha.0+snapshot-6.20260207.040922"
        }
      ]
    },
    {
      "name": "modDevRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "11.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "earlydisplay",
          "version": {
            "requires": "11.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "org.lwjgl",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "11.0.2"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.7"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.9"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.16.5+mixin.0.8.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "26.1-snapshot-6-1"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform-dependencies"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-dependencies",
          "version": "26.1.0.0-alpha.0+snapshot-6.20260207.040922"
        }
      ]
    },
    {
      "name": "modDevModulePath",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external"
      },
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-module-path",
          "version": "26.1.0.0-alpha.0+snapshot-6.20260207.040922"
        }
      ]
    },
    {
      "name": "modDevTestFixtures",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "junit-fml",
          "version": {
            "requires": "11.0.0"
          },
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-test-fixtures",
          "version": "26.1.0.0-alpha.0+snapshot-6.20260207.040922"
        }
      ]
    }
  ]
}
