{
  "formatVersion": "1.1",
  "component": {
    "group": "org.academy",
    "module": "misaka-network",
    "version": "21.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "misaka-network-21.10.1.jar",
          "url": "misaka-network-21.10.1.jar",
          "size": 62736,
          "sha512": "cb8987b8050318fcd78f910c2ab8d15677e4381a53d68fd68fb8877cee883809f8036e14deadfac2512e134a4d9f729806062fbb278fb298f5a1f3519f2021f8",
          "sha256": "df286856accff0bca1e06fe4bb15dcb56ef02495c29c1902226d7d5aaf1a626a",
          "sha1": "b9c56c13daf82d6b09899d2765e20794e92f47c4",
          "md5": "5bf96214d9e08e9b6b7f8966fe5724be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "misaka-network-21.10.1.jar",
          "url": "misaka-network-21.10.1.jar",
          "size": 62736,
          "sha512": "cb8987b8050318fcd78f910c2ab8d15677e4381a53d68fd68fb8877cee883809f8036e14deadfac2512e134a4d9f729806062fbb278fb298f5a1f3519f2021f8",
          "sha256": "df286856accff0bca1e06fe4bb15dcb56ef02495c29c1902226d7d5aaf1a626a",
          "sha1": "b9c56c13daf82d6b09899d2765e20794e92f47c4",
          "md5": "5bf96214d9e08e9b6b7f8966fe5724be"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "misaka-network-21.10.1-sources.jar",
          "url": "misaka-network-21.10.1-sources.jar",
          "size": 35411,
          "sha512": "b3c7522a2ebe67a57fc8187ab647fd8358a7b4c877d4252ba0e4b6ae61f9da44366bb6f56f0376a8f018b6bb048fec2031a28e607665764d55e56fbbf18a37a7",
          "sha256": "15667b314abc7fc6a14be32a6a589939809b8a51f99a180fc3c811e1d7594ce2",
          "sha1": "71ce3b67a215b280505805f6e7e1158ddfa337c7",
          "md5": "c2a26452bf53b4c4766b87f99f7cf4cf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "misaka-network-21.10.1-javadoc.jar",
          "url": "misaka-network-21.10.1-javadoc.jar",
          "size": 249071,
          "sha512": "58cf8f83976662567b9368e686665f4cd3443319eb00c7be5aea3f48b4a6bf7d8c30fa590392ca7e15484a8ecd7b5e4f6ee9ca3a8da370c5d684f578e4041d1f",
          "sha256": "521f3d23785b73a9a0c7693b289b5fe58e09c14375822e10d80e516611e1f8d7",
          "sha1": "7259e1592c5ce735eaf949fcb54191c7af63d272",
          "md5": "723e044858eefc5f8ac667e0a96d840a"
        }
      ]
    }
  ]
}
