{
  "formatVersion": "1.1",
  "component": {
    "group": "org.academy",
    "module": "misaka-network",
    "version": "21.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "misaka-network-21.10.1.jar",
          "url": "misaka-network-21.10.1.jar",
          "size": 62249,
          "sha512": "b19a1554d8ae069e36a73bca574f09c62e30f84829a4771ff85e09c3f1edca9b8c5bdcb82f922c704ec64ec0211484129b210626f73b9bbd270197c2e4068d1b",
          "sha256": "fd71c00e7904b171f62f43b5f91e422f617dd8c44f3d45f33defaef5cd5eebbc",
          "sha1": "ad19541986fcb1a4701d2ab85f27a04d12b5f356",
          "md5": "da4dfca7c48275409127fb544bfda39b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "misaka-network-21.10.1.jar",
          "url": "misaka-network-21.10.1.jar",
          "size": 62249,
          "sha512": "b19a1554d8ae069e36a73bca574f09c62e30f84829a4771ff85e09c3f1edca9b8c5bdcb82f922c704ec64ec0211484129b210626f73b9bbd270197c2e4068d1b",
          "sha256": "fd71c00e7904b171f62f43b5f91e422f617dd8c44f3d45f33defaef5cd5eebbc",
          "sha1": "ad19541986fcb1a4701d2ab85f27a04d12b5f356",
          "md5": "da4dfca7c48275409127fb544bfda39b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "misaka-network-21.10.1-sources.jar",
          "url": "misaka-network-21.10.1-sources.jar",
          "size": 34131,
          "sha512": "741325d8e5d946eed5b1114b228b13b13c7258f1ddfa4c21adc0163dcf3ff99de6fa9b9629615afae8bc3f45b98af24dec12f5081fa25dfd97121dbdad845767",
          "sha256": "99fce876f563af24ad9e992e381f0b3b73a8b42a26bde04ab15f8c2ce7601115",
          "sha1": "667b8a75267830da4f1222df000fad1e43a7026b",
          "md5": "b34cf7aa72994797b01f72b95c849878"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "misaka-network-21.10.1-javadoc.jar",
          "url": "misaka-network-21.10.1-javadoc.jar",
          "size": 240097,
          "sha512": "037144bdaffa16177c0ac5559ccaaf89774a0257b4e8420ef45a37c6ee1b6f9c9c350b2bdb0c5dfb141fcb776f356215c6edfae59f11d22a8ff34c0a0420cd2b",
          "sha256": "f3381a48989980a4431f87eaf672fe2b671adc8421aa0465c4ccb65642cbb1ac",
          "sha1": "a826f6b3e417197f12dbd4c896822067c0f03dff",
          "md5": "c55fa6347b4eae39c61736ef864fb479"
        }
      ]
    }
  ]
}
