{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged",
    "module": "neoforge",
    "version": "26.1.0-alpha.26.1-snapshot-1.20251220.085055",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-26.1.0-alpha.26.1-snapshot-1.20251220.085055-sources.jar",
          "url": "neoforge-26.1.0-alpha.26.1-snapshot-1.20251220.085055-sources.jar",
          "size": 2006941,
          "sha512": "4ecb03b5c27d277b669b4b4da63cb19ec412bbc010e7de55e865901f639c28eca5a4796bf9ac3685d492dcaa89b3d1669aaaf2a12bd8dde57b44c55352b1930d",
          "sha256": "ec63924260bba4e1e460a8c4ec7a2cbeae3c9c82c29e29452cf511374317162d",
          "sha1": "71514ae271060291d7d79c392975fd8e84ffad23",
          "md5": "a556bb12786ba7c254a6f460470556ef"
        }
      ]
    },
    {
      "name": "modDevBundle",
      "attributes": {
        "org.gradle.category": "data",
        "org.gradle.dependency.bundling": "external"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "26.1-snapshot-1-2"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "neoforge-26.1.0-alpha.26.1-snapshot-1.20251220.085055-userdev.jar",
          "url": "neoforge-26.1.0-alpha.26.1-snapshot-1.20251220.085055-userdev.jar",
          "size": 4346209,
          "sha512": "c361bb6842cbea823dda6317794782721693e48d20f9b5d6bd84b963edd21c3ee23354ac56fdc36128002f8b442fd4825744e014222bbcdd93fde10daf00e0a7",
          "sha256": "1f69e9de35110718f7b23c51a57e7f566f042e8acc01865b23d425f3acb45782",
          "sha1": "2e9c5027171d192a8ea2edc849a333b0e6350099",
          "md5": "a7afe288d92cab1c0a5eaa0b1c76f032"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-bundle",
          "version": "26.1.0-alpha.26.1-snapshot-1.20251220.085055"
        }
      ]
    },
    {
      "name": "modDevConfig",
      "attributes": {
        "org.gradle.category": "data",
        "org.gradle.dependency.bundling": "external"
      },
      "files": [
        {
          "name": "neoforge-26.1.0-alpha.26.1-snapshot-1.20251220.085055-moddev-config.json",
          "url": "neoforge-26.1.0-alpha.26.1-snapshot-1.20251220.085055-moddev-config.json",
          "size": 7203,
          "sha512": "0d9ed4405165cb69ce75f42ad4224a14c4b5c9cea1189780eab5826d790719340e4268ffecd16fc654f3cb1e45fe7157c04885c587972e55ffee4589cfe1aba8",
          "sha256": "03268692690e0802376394a0e19d75711944c7dfbf38c929fd43465d1677d186",
          "sha1": "985fe7e3cc38744de46c389fa9f10fc3ed6f905f",
          "md5": "242efd746723545e9e04241117861c1e"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-config",
          "version": "26.1.0-alpha.26.1-snapshot-1.20251220.085055"
        }
      ]
    },
    {
      "name": "installerJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-26.1.0-alpha.26.1-snapshot-1.20251220.085055-installer.jar",
          "url": "neoforge-26.1.0-alpha.26.1-snapshot-1.20251220.085055-installer.jar",
          "size": 11008201,
          "sha512": "ce191ae86014ba3341e011db485a2d9d145e35cb0bc936ca875204c07994e3e051576eca88eed7190a998a16b8a4b466308e475880cd5b47ca2d9302571651d5",
          "sha256": "ffee1081bef58bedbc40cb64ac6912d6c28144ffb062aa6c8f605924e9383e8f",
          "sha1": "56d423409cfba25f867e23a60672446256613cd9",
          "md5": "66723a47c86104d7a5db70ad972c93b0"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-installer",
          "version": "26.1.0-alpha.26.1-snapshot-1.20251220.085055"
        }
      ]
    },
    {
      "name": "universalJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-26.1.0-alpha.26.1-snapshot-1.20251220.085055-universal.jar",
          "url": "neoforge-26.1.0-alpha.26.1-snapshot-1.20251220.085055-universal.jar",
          "size": 7369336,
          "sha512": "9b47898c79086f2f82b9a0d98863e8d1646a6989dc25942312b59d35607e7b7ba7756d72341d05c58673fa69eb177069e1812ddac72f0a9d2adc444a9c3727eb",
          "sha256": "9873bc8b104cd3f4c2350036e822ee74ba19e4ab1dd91397efadeda736c91a0f",
          "sha1": "2b7d7e7912ce2224957f23386c6590ea2f8a084d",
          "md5": "7630a0a9b794d24c781baba184786d64"
        }
      ]
    },
    {
      "name": "modDevApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "11.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "earlydisplay",
          "version": {
            "requires": "11.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "org.lwjgl",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "11.0.2"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.7"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.9"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.16.5+mixin.0.8.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "26.1-snapshot-1-2"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform-dependencies"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-dependencies",
          "version": "26.1.0-alpha.26.1-snapshot-1.20251220.085055"
        }
      ]
    },
    {
      "name": "modDevRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "strictly": "9.9.1",
            "requires": "9.9.1"
          }
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "11.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "earlydisplay",
          "version": {
            "requires": "11.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "org.lwjgl",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "11.0.2"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.7"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.9"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.16.5+mixin.0.8.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "26.1-snapshot-1-2"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform-dependencies"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-dependencies",
          "version": "26.1.0-alpha.26.1-snapshot-1.20251220.085055"
        }
      ]
    },
    {
      "name": "modDevModulePath",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external"
      },
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-module-path",
          "version": "26.1.0-alpha.26.1-snapshot-1.20251220.085055"
        }
      ]
    },
    {
      "name": "modDevTestFixtures",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "junit-fml",
          "version": {
            "requires": "11.0.0"
          },
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-test-fixtures",
          "version": "26.1.0-alpha.26.1-snapshot-1.20251220.085055"
        }
      ]
    }
  ]
}
